name 'irksome-sniffle'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures irksome-sniffle'
long_description 'Installs/Configures irksome-sniffle'
version '0.1.0'
